### ISSUE TITLE
Exporter resolve my FQDN and return a 404 code

### ISSUE THREAD

**Issue by Piknik1990** [infinityworks/hpilo-exporter#10]
Hello! 
Thanks you a lot for a fine exporter. 

The one bug:
I have a two ILO-servers by https connections. In https I was customizated selfsign SSL certs for domain name "ilo.master.my.org" and add this domain to the hosts-file

`192.168.1.14 ilo.master.my.org`

My Prometheus configuration is:

```
  - job_name: 'hpilo-master'
    scrape_interval: 1m
    params:
      ilo_port: ['443']
      ilo_user: ['Administrator']
      ilo_password: ['secret']
    static_configs:
      - targets:
        - ilo.master.my.org
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_ilo_host
      - source_labels: [__param_ilo_host]
        target_label: ilo_host
      - target_label: __address__
        replacement: master:9416
```

Prometheus sending http-request a correct:

`prometheus[8021]: level=debug ts=2020-01-10T20:39:07.840Z caller=scrape.go:920 component="scrape manager" scrape_pool=hpilo-master target="http://master:9416/metrics?ilo_host=ilo.master.my.org&ilo_password=secret&ilo_port=443&ilo_user=Administrator" msg="Scrape failed" err="Get http://master:9416/metrics?ilo_host=ilo.master.my.org&ilo_password=secret&ilo_port=443&ilo_user=Administrator: EOF"`

but hpilo_exporter resolve my FQDN to IP and this is broken my HTTPS-logic:

`hpilo-exporter[6163]: 192.168.1.8 - - [07/Jan/2020 04:06:13] "GET /metrics?ilo_host=192.168.1.14&ilo_password=secret&ilo_port=443&ilo_user=Administrator HTTP/1.1" 404 -`

Of course, this is not work and return 404 code to me. 

On my host with installed hpilo_exporter SSL work is fine, but this broken SSL logic.

My hpilo_exporter ran like here:
```
● hpilo-exporter.service - HPILO Exporter
   Loaded: loaded (/etc/systemd/system/hpilo-exporter.service; enabled; vendor preset: disabled)
   Active: active (running) since Пт 2020-01-10 23:57:48 MSK; 3s ago
 Main PID: 50145 (hpilo-exporter)
    Tasks: 1
   CGroup: /system.slice/hpilo-exporter.service
           └─50145 /usr/bin/python2 /bin/hpilo-exporter --address=0.0.0.0 --port=9416 --endpoint="/metrics"


```
